export const conditions = [
  // "numPages",
  // "numberOfVolumes",
  "abstractNote",
  "anyField",
  // "accessDate",
  // "applicationNumber",
  // "archive",
  // "artworkSize",
  // "assignee",
  // "fulltextContent",
  // "fileTypeID",
  // "author",
  // "authority",
  // "bookAuthor",
  // "callNumber",
  // "childNote",
  // "citationKey",
  // "code",
  // "codeNumber",
  "collection",
  // "committee",
  // "conferenceName",
  // "country",
  "creator",
  "date",
  "dateAdded",
  "dateModified",
  // "DOI",
  // "edition",
  // "editor",
  // "extra",
  // "filingDate",
  // "history",
  // "ISBN",
  // "ISSN",
  // "issue",
  "itemType",
  // "journalAbbreviation",
  // "language",
  // "libraryCatalog",
  // "archiveLocation",
  // "medium",
  // "meetingName",
  "note",
  // "number",
  // "pages",
  // "place",
  // "priorityNumbers",
  // "programmingLanguage",
  // "publicationTitle",
  // "publisher",
  // "references",
  // "reporter",
  // "rights",
  // "runningTime",
  // "scale",
  // "section",
  // "series",
  // "seriesNumber",
  // "seriesText",
  // "seriesTitle",
  // "session",
  // "shortTitle",
  // "status",
  // "system",
  "tag",
  "title",
  "type",
  // "url",
  // "versionNumber",
  // "volume",
  // "deleted",
  // "noChildren",
  // "unfiled",
  // "retracted",
  // "publications",
  // "feed",
  // "includeParentsAndChildren",
  // "includeParents",
  // "includeChildren",
  // "recursive",
  // "joinMode",
  // "quicksearch-titleCreatorYear",
  // "quicksearch-titleCreatorYearNote",
  // "quicksearch-fields",
  // "quicksearch-everything",
  // "quicksearch",
  // "blockStart",
  // "blockEnd",
  // "collectionID",
  // "savedSearchID",
  // "savedSearch",
  // "itemTypeID",
  // "tagID",
  // "lastName",
  // "field",
  // "datefield",
  // "year",
  // "numberfield",
  "libraryID",
  // "key",
  // "itemID",
  // "annotationText",
  // "annotationComment",
  // "fulltextWord",
  // "tempTable",
] as const

export const operators = [
  "contains",
  "doesNotContain",
  "is",
  "isNot",
  "beginsWith",
  "isBefore",
  "isAfter"
] as const